### ISSUE TITLE
"Documentation" and "Report A Bug" buttons

### ISSUE THREAD

**Issue by xan2622** [aresdevo/animaide#1]
Hi.

In the bl_info paragraph of your `__init__.py` python file, maybe you could add these two clickable buttons in the Preferences > Addon details:

<img width="890" alt="Documentation_ReportABug" src="https://user-images.githubusercontent.com/1732773/59555523-f5f67b00-8fb3-11e9-8e7b-117ec28a72e3.png">

"wiki_url": "https://github.com/aresdevo/animaide",
"tracker_url: "https://github.com/aresdevo/animaide/issues",

**Comment by aresdevo** [comment]
Thanks a lot. I'll do that right away

**Comment by aresdevo** [comment]
Done. Thanks again
