### ISSUE TITLE
Sliders disapear in Pose Mode

### ISSUE THREAD

**Issue by lucianomunoz** [aresdevo/animaide#11]
In pose mode the sliders completely  disapear.

![Capture-Blender_  D__Dropbox_001_Current_Projects_Raptorex_Rig_RAPTOREX_MuscleSystem_Rig-2019-08-08 01_06_44](https://user-images.githubusercontent.com/5134226/62634240-e32b7180-b978-11e9-8af1-ede85fd579b2.png)

any idea why?

**Comment by aresdevo** [comment]
I can not replicate it. Try running Blender from the shell to see if there are any error messages there when you try it.

**Comment by Irmitya** [comment]
> I can not replicate it. Try running Blender from the shell to see if there are any error messages there when you try it.

I get when a developer tells people to do that, because it's something like a crash where you CAN'T use Blender anymore but why are you? Are you not aware of this button?
![image](https://user-images.githubusercontent.com/10817631/62646353-c741b480-b913-11e9-8f5d-a30a2b602445.png)

**Comment by Pullusb** [comment]
@Irmitya I think console toggle is available only on windows. On Linux/Mac you must launch from a terminal. And It's not usefull only for crashes, you can have some usefull display there without crashing. That's what @aresdevo  wanted to check.

**Comment by aresdevo** [comment]
Exactly.
I only have access to Mac and Linux at the moment, and they can only have access to the shell if Blender runs from it. On Mac Blender will run from a shell if you use the icon inside "package contents" (Blender.app/Contents/MacOS/Blender), I have an alias of that icon on my dock. I forgot windows have that option in Blender though. I will remember next time to ask the user what OS is using.

**Comment by aresdevo** [comment]
Is this still an issue?
