### ISSUE TITLE
Anim Transform breaks fcurves for additive layers

### ISSUE THREAD

**Issue by Irmitya** [aresdevo/animaide#12]
Initially I was getting a problem in my rig where only the regular actions would work, and when trying to use AnTr with my "layers", it would never update the fcurves. 

I'm in multi-pose mode and sometimes some of the rigs fail to be found by Blender, so I switched to Single-object pose. 
I finally got AnTr to update my Fcurves. The problem is it consistently blew things up out of proportion, regardless at to whether or not I'm even doing something to the bone(s) _(related to me using a viewport camera object)_

here's a cube:
[AnimTransforms.zip](https://github.com/aresdevo/animaide/files/3484491/AnimTransforms.zip)

**_unrelated_**: there are some more bugs so I was/am starting to redo line of code; mostly at many conditional polls _(inside functions)_
one error for example is obj_anim checks itself then assumes it has an action and checks that action's fcurves, and another _(not error)_ is how fcurve without a group are ignored which isn't necessary

**Comment by aresdevo** [comment]
Thanks again for the attention you are paying to the addon. 

> Initially I was getting a problem in my rig where only the regular actions would work, and when trying to use AnTr with my "layers", it would never update the fcurves.

Layers are something I have not included in the addon (don't expect Animaide to work with them at the moment). Don't think the sliders need to take them into account since they don't show the f-curves in the graph editor, but the user would expect AnimTransform to work with it. It is something I have to work on. So many things I should have said in the readme!

> I'm in multi-pose mode and sometimes some of the rigs fail to be found by Blender, so I switched to Single-object pose.

I'm very interested in knowing when that fails because is something I worked on and thought was working.

>I finally got AnTr to update my Fcurves. The problem is it consistently blew things up out of proportion, regardless at to whether or not I'm even doing something to the bone(s) (related to me using a viewport camera object)

Don't understand what you mean here, but did check the file you sent and I see that the cube goes crazy when I use AnimTransform since it is using layers. As had not taken layers into consideration in my code. Something I need to work on.

> there are some more bugs so I was/am starting to redo line of code; mostly at many conditional polls (inside functions)

Oh... please re-download the addon (I just uploaded it). I deleted some old unused code and added documentation. I would like you to work on the latest one.

> one error for example is obj_anim checks itself then assumes it has an action and checks that action's fcurves

hmmm... The obj_anim checks itself?! that is bad. I thought I have added a check for the action though. I'll check

>and another (not error) is how fcurve without a group are ignored which isn't necessary

That actually was added to fix a [bug](https://github.com/aresdevo/animaide/issues/9) . Didn't think I needed that but it turns out that if you have an action that it has some deleted bones Blender will intrepret that group as "None".

Thanks again for checking the addon in depth. If you change or add any code please share it. I'm just an animator trying to do some coding and need all the help I can get.

I'll be traveling for the next couple of weeks so I might not be as active as I want here, but I will do my best.

**Comment by aresdevo** [comment]
I see what you say about obj_anim checking itself:
 
 ```
obj_anim = obj.animation_data

if obj_anim is None:
    return
```

The thing is that "obj.animation_data" sometimes is "None". So I'm not checking if I have created the object, I'm checking to see if the value of the object is "None".

So I guess another version of the same code could have been:

 ```
if obj.animation_data is None:
    return

obj_anim = obj.animation_data
```

But don't see any of it causing any issue with the code

**Comment by aresdevo** [comment]
> then assumes it has an action and checks that action's fcurves

I did that because I could not find a way to create animation data on an object without adding an action, so I assumed there would never be animation data without an action. But I assumed wrong before with the groups so maybe I should check for the action just in case.

**Comment by aresdevo** [comment]
I will try to tackle the animation layers next. I will let you know when/if I have done anything.

**Comment by aresdevo** [comment]
Ok... started to dig into the animation layers in Blender, and when I replicate your cube scene (not load yours but create a new one from scratch) everything works like if I don't have to do anything for the layers to work with AnimAide. There is something special about your scene. I think if I find what it is would be the keys to solving this issue. I thought maybe it was the fact that you added as a strip the same action you are modifying, but that works fine in my scene. What a mistery

**Comment by aresdevo** [comment]
Oh... The issue happens when you use anything other than "Replace" on the "action blending" in the animation data. 

Sorry for this monologue. I just realized it might be annoying. I will keep working and hold on the comments until you reply.

**Comment by Irmitya** [comment]
I _"assume"_ that you use the exact value from the transforms as what to use for what's in the keyframes.  

Keyframe values for layers are inserted specifically for their Blend type, then the system does math to combine them, BASED on their Blend type.  Keyframe insertion is more like a recent fix to the old system, where keyframe insertion DID only insert based on the final transforms values _(but the animation system still needed different values to work how you would expect)_.

- - - -

In my code that searches for "selected objects", I essentially do to separate checks. 
1) In pose mode, it searches for ALL objects in the scene, and filters them down to if they're in pose mode. 
2) In any other mode, it searches for all objects that are selected. 

I don't know the exact circumstances to run into an instance where a rig is in pose mode, you can select its bones just like the other rigs but the rig object itself is NOT selected. 
I just know that sometimes it happens, so I just workaround it by not checking if the rig is actually selected.

The thing about it is selecting the bones doesn't select the rig, just make it the active object. In order to select the object from Pose mode, you have to go to Object mode, select the objects, _(then back to Pose mode)_

 - - - -
```
    action = None

    if 'animaide' in bpy.data.actions:
        action = bpy.data.actions['animaide']

    if action is None:
        return

    if action.fcurves.items() == []:
        return
```

My issues with this is two separate **IF** checks that only purpose is to exit the function, to not run into an error when running the code, and how you search for **action**.
 It "functions" as intended but I just don't like how it's inserted. 
```
    action = bpy.data.actions.get('animaide')

    if action is None or action.fcurves.items() == []:
        # I also prefer it be "or not action.fcurves"
        return
```
I also like wrapping conditions in an IF line in parenthesis, for visual separation but I'm not going to bother with that.
- - - -

That's a cosmetic thing but there are **functional** issues such as the obj_anim. 

The problem isn't how you check animation_data _(though I don't like the name obj_anim)_. 

The problem is you don't check for an **_action_**

`anim = obj.animation_data_create()` 
will always return the animation_data or create it if it doesn't exist. 

You COULD do this but I prefer you don't.  If something has animation data, it should be because you inserted a keyframe on it before, not as a byproduct somewhere in the addon. 

What I prefer here is something like:
```
        anim = obj.animation_data

        if getattr(anim, 'action', None) is None or anim.action.fcurves is None:
            return
```
or maybe
```
        action = getattr(obj.animation_data, 'action', None)
        fcurves = getattr(action, 'fcurves', None)

        if fcurves is None:
            return
```

- - - -
As for the "groups" thing, you ignore curves if they don't have a group but you do that because otherwise you get an error when checking for the group's name. No other functional reason for the group check. 

Which is unnecessary because you can do this instead:
 ```
    if fcurve.group and fcurve.group.name == cur_utils.group_name:
        return  # we don't want to select keys on reference fcurves
```

When doing a poll thing, Python checks the first condition; if it's False and an **or** clause isn't specified, it skips the rest of the conditions. 
A tuple/list check such as "any/all", checks all the items _(unless the line's condition is False like in an **IF**)_

- - - - 

The issue with sharing my changes is where I'm making them. 

_**First:**_  I  use Pylinting in VSCode _(with PEP8 standards; minus "some" rules)_. 
_**Second:**_ I put the code of this addon (and my changed) in a subfolder of my addon. 

I was elaborating on these two factors but that's a bunch of extra text. 
Point is, I would have to do some extra stuff in order to submit the changes I make. 

The things I mentioned above is mostly what I plan to do and I've only looked into magnet.py so I don't know what I would need to do in the other files and just "expect" there to be more to do so I'm just putting it off because I have some other tasks of my own to do _(animating and my own addon)_.

**Comment by aresdevo** [comment]
Well... thanks for the feedback anyway. This is my first addon and I'm learning a lot in the process. 

Part of the reason I use so many IF statements in different lines (instead of combining them into one) is that I saw Sybren Stüvel's curse "Scripting for Artists" in the Blender cloud and he likes that approach.

I was not aware of the "get" functionality, like in bpy.data.actions.get(). I now need to go through all of my code and check if I can make it more efficient with it. I know I have used "for" loops for things I could have use the get function.

**Comment by aresdevo** [comment]
By the way, was checking your work and love "CendaTools"

**Comment by Irmitya** [comment]
> By the way, was checking your work and love "CendaTools"

That's a fork. 
At some point I gave them code for the slider (because of a situation it could be used in that they didn't test, where Blender is weird about), and another thing. 

But all the fork is, is a 2.7 x 2.8 compatible version because they never made it for 2.8. I don't know if they ever got around to doing it; didn't bother checking.

**Comment by Irmitya** [comment]
> > I'm in multi-pose mode and sometimes some of the rigs fail to be found by Blender, so I switched to Single-object pose.
> 
> I'm very interested in knowing when that fails because is something I worked on and thought was working.

I'm rewriting one of my things, and found a note I made explaining a time this happens. 

If you toggle a collection off/on, all the objects in it get deselected. 
When the object is visible again, it's still in pose mode and you can press A to select the bones, use box-select, etc but the object remains un-selected. 

I don't know if this was something later fixed or I just find it inconvenient but if you Click-select the bone, it's object gets set active and also marks the object as selected. 

I probably just found this inconvenient because when I need to find the _(selected)_ pose-objects, I prefer to select all or box-select, instead of having to manually click a different bone from like 5 different rigs, just to make sure they're found in the selection.

**Comment by aresdevo** [comment]
Too old of a bug to track
