### ISSUE TITLE
Push Pull broken after last commit

### ISSUE THREAD

**Issue by Irmitya** [aresdevo/animaide#15]
In the commit `cleaning code`, you deleted `def linear_y()` from `key_utils.py`
8f405857ecebce537a7dfa16c69803527e1da619

This function is used by the Push/Pull operator, and so when calling it, it gives an error.

**Comment by aresdevo** [comment]
I took it out because I didn't need it as a separate function. Apparently forgot to replace the code in push-pull. Let me check

**Comment by aresdevo** [comment]
I added the function back. Thanks for catching that. I have not uploaded the change though because I need to merge your code before I introduce any change.

I should start to use branches and not work on the master.

**Comment by aresdevo** [comment]
So I merged your branch, but I messed it up when pulling the code to my computer, so when I added the function missing for Push-Pull I didn't realize I was working with the old file, so when I committed the code now I don't think it has the changes you made. I'm trying to figure out how to bring it back, but I'm new at this

**Comment by aresdevo** [comment]
Ok, I figured it out.
