### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by justausernamesfm** [aresdevo/animaide#2]
Using version 2.80.75 of Blender.

So I download the zip, go to preferences, add-ons, install, double click the zip, on the bottom it says modules moved to the addons folder... but there's no AnimAide in the list, not under user and not if I search for it. There is an animaide folder in \AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons. Tried installing other addons and they work fine.

**Comment by Likkkez** [comment]
Yep, same problem on version 2.81

**Comment by PluffyFX** [comment]
Same problem on latest build. After clicking install it says copying files at the bottom, but nothing seems to actually happen. Have tried refreshing, restarting application, re-downloading and copying the files over manually. Nothing seems to work.

**Comment by TheHoodieGuy02** [comment]
![Capture](https://user-images.githubusercontent.com/26211033/62211964-0a5acf80-b3ca-11e9-9721-7f29c0105649.PNG)

Same problem here on "retail" release of 2.80
The file does copied over to the addons folder, but isn't detected in the Add-ons list. The message doesn't even shows the add-on title in the brackets, unlike other successfully installed add-ons.
`Modules installed () from <source directory> to <install directory>`

**Comment by Likkkez** [comment]
I've figured it out boys. Edit '__init__.py' and add " symbol right after tracker_url on line 36 so it looks like this:
`    "tracker_url": "https://github.com/aresdevo/animaide/issues"`

**Comment by Likkkez** [comment]
Actually, nvm the last message. It had a few other typos in there for some reason. Here's the actual blender info u need to replace inside __init__.py and then it works.
```
bl_info = {
    "name": "AnimAide",
    "description": "",
    "author": "Ares Deveaux",
    "version": (0, 1, 0),
    "blender": (2, 80, 0),
    "location": "Graph Editor > Side Panel",
    "warning": "This addon is still in development.",
    "wiki_url": "",
    "category": "Animation",
    "wiki_url": "https://github.com/aresdevo/animaide",
    "tracker_url": "https://github.com/aresdevo/animaide/issues"
}
```

**Comment by aresdevo** [comment]
I think the issue is solved now. Thanks for pointing that up
