### ISSUE TITLE
sometimes the tool affects unnintended keyframes. (any slider)

### ISSUE THREAD

**Issue by lucianomunoz** [aresdevo/animaide#21]
So sometimes i have this i select 4 subsequent keyframes, and use say ease to ease, then i realize i only want to do it to 3 of the for, so i deselect one (the first one usually), and when i use the ease to ease or any other slider via the sliders or hotkeys or even thepie menus, the 4 initial keys are affected:
here is a little descriptive gif.

![slider](https://user-images.githubusercontent.com/5134226/71581901-b9f3c380-2b5b-11ea-9234-593df9f630e4.gif)

**Comment by lucianomunoz** [comment]
so no fix on this?

**Comment by Irmitya** [comment]
What happens is Blender's select operators don't update the select variable on all keyframes, just internally, therefore any Python operation that checks their selection, can get inaccurate results.
I made a function that calls an operator that DOES update the selection and insert it at the start of operators that find selected keyframes.

```
    def update_keyframe_points(context):
        """# The select operator(s) are bugged, and can fail to update selected keys, so"""
        area = context.area.type
        if area != 'GRAPH_EDITOR':
            context.area.type = 'GRAPH_EDITOR'

        bpy.ops.transform.transform()

        if area != 'GRAPH_EDITOR':
            context.area.type = area
```

I put it in animade/slider_tools.py / `def invoke`

I made several changes to my version of this addon (I didn't upload them to my fork). I don't remember how this version's code works so you probably would have to add it to execute too. Idk+Idc

**Comment by lucianomunoz** [comment]
Ah man, i have no idea about coding, that's too bad :/

**Comment by Irmitya** [comment]
It's not that hard. 
I pushed my changes to my fork but the way I call this function is by first importing it from a separate "utilities" file/addon that I make for _**my**_ addons. Meaning it doesn't work as is for others _(error)_ and I've no intention of creating a separate "publishing" version of my github(s).

Way I see it, best case, @aresdevo abandoned this addon and maybe their account(s), disabled email notifications and/or don't want to chat anymore
Worst case: in the past 6 months, they died. 

Either case, there's not going to be any updates by them, leaving a void for others to pick up where @aresdevo left off, and if you cared enough, you could fill it yourself; it won't be done me.

**Comment by lucianomunoz** [comment]
holy crap i didnt realize it was someone else that answered, damn, thanks I'll try, best case scenario i learn, worse case scenario i get a friend to fix it and fork it for me . 
and we bring it back to life.

**Comment by lucianomunoz** [comment]
thank you for that extra bits of code.

**Comment by aresdevo** [comment]
Sorry I have abandoned this project. This year has been crazy. I had to deal with some personal issues but things are looking better at the moment. 

I will make sure this is part of master

**Comment by aresdevo** [comment]
This bug was addressed by @Irmitya in one of his commits. I have spent a few weeks going through the code enhancing the add-on and fixing bugs. I just publish it and called it version 1.0. This bug fix is in this new version.

Please let me know how things work for you.
