### ISSUE TITLE
Cannot move a bone in Animtransform mode

### ISSUE THREAD

**Issue by DaitomodachiChannel** [aresdevo/animaide#23]
There times when I activate Animtransform mode and the bones does not move at all even though I have the keyframes selected

**Comment by wbmoss** [comment]
This comment is for the author, the fix is to replace "return" with "continue" in manget.py on line 61 and 80.
![animaide_fix](https://user-images.githubusercontent.com/28886285/81486672-5cb40100-9224-11ea-9b8d-bfb75880f3ab.gif)

**Comment by aresdevo** [comment]
Sorry I have abandoned this project. This year has been crazy. I had to deal with some personal issues but things are looking better at the moment. 

Thanks @wbmoss for the suggestion.

I know I need to address a lot of bugs but, if it helps, somebody is adding a [similar tool in Blender](https://developer.blender.org/T81836). You can download there a build for Linux and Windows.

**Comment by aresdevo** [comment]
I have spent a few weeks going through the code enhancing the add-on and fixing bugs. Hopefully, I have addressed most of them.

This specific bug seems to be addressed by one of @Irmitya commits.

I just publish it and call it version 1.0. Please let me know how things work for you.

**Comment by DaitomodachiChannel** [comment]
Will do! Good to see you back on this!

**Comment by aresdevo** [comment]
Hey, thanks @DaitomodachiChannel. 
Just wanted to let you know that I just added a new revision. There is a new option to activate the curveTools. Learn more about it in the readme (it is highlighted in the "new in this version").
If you already downloaded the addon, please download it again and let me know what you think.
Thanks again.
![active_on_release](https://user-images.githubusercontent.com/16739268/104990855-53de1680-59d2-11eb-80ef-e3120f5fd84d.gif)
