### ISSUE TITLE
Can't Activate Add-on

### ISSUE THREAD

**Issue by avallintine** [aresdevo/animaide#29]
Windows 10, Blender 2.83.10 and 2.91.2

Add-on appears to install fine from downloaded .zip, but when checking box to activate, it does not activate and get message in console:

addon not found: 'animaide-master'

:cry:

**Comment by avallintine** [comment]
When trying to import from Blender Python console:

```
>>> import animaide
Traceback (most recent call last):
  File "<blender_console>", line 1, in <module>
  File "C:\Users\avallintine\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\animaide\__init__.py", line 37, in <module>
    from . import ui, curve_tools, anim_offset, key_manager
ImportError: cannot import name 'key_manager' from 'animaide' (C:\Users\avallintine\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\animaide\__init__.py)
```

Where is this key_manager?

**Comment by avallintine** [comment]
I removed the import of key_manager from __init__.py and everything seems to be working fine now.

This looks like a great add-on and will definitely come in handy editing mocap animation! Really glad I found it!

**Comment by lucianomunoz** [comment]
well that makes the sliders completely useless.. :/

**Comment by aresdevo** [comment]
Sorry about that... it should be fixed now. Implementing new tools and by mistake added that to master.

**Comment by aresdevo** [comment]
Thanks @avallintine, you made the bug fixing job way easier for me. It turns out that I could not reproduce the problem because I do have keyManager on my computer. Now I have another install of Blender that can not access my development folder to more accurately find bugs.

**Comment by aresdevo** [comment]
Please, let me know if is working for you now

**Comment by avallintine** [comment]
Fixed!
