### ISSUE TITLE
Support for 2.83 LTS?

### ISSUE THREAD

**Issue by avallintine** [aresdevo/animaide#30]
I couldn't find any mention of which Blender versions are supported so I thought I'd ask. Do you intend to support 2.83 LTS? Is it worth mentioning bugs found in 2.83 but not 2.91?

**Comment by aresdevo** [comment]
hmmm... Never thought of that. I would say yes. I need to create a new branch for that.

**Comment by avallintine** [comment]
Great, glad to hear you'll try to support it.
