### ISSUE TITLE
Can't Set Reference Frames in Blender 2.83

### ISSUE THREAD

**Issue by avallintine** [aresdevo/animaide#32]
When clicking one of the buttons to set a reference frame you get this exception:

```
Traceback (most recent call last):
  File "C:\Users\avallintine\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\animaide-master\curve_tools\ops.py", line 800, in execute
    utils.add_marker(name='', side=self.side, frame=current_frame)
  File "C:\Users\avallintine\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\animaide-master\utils\general.py", line 83, in add_marker
    marker['side'] = side
TypeError: bpy_struct[key] = val: id properties not supported for this type
```

I did a little digging into this and setting properties in this way appears to behave differently between 2.83 and 2.91. For instance, in 2.91:

```
>>> m = bpy.context.scene.timeline_markers.new("marker")
>>> m['side'] = 'L'
>>> m['side']
'L'
```

However, in 2.83:

```
>>> m = bpy.context.scene.timeline_markers.new("marker")
>>> m['side'] = 'L'
Traceback (most recent call last):
  File "<blender_console>", line 1, in <module>
TypeError: bpy_struct[key] = val: id properties not supported for this type
```

To be honest, I don't understand why it works in 2.91 but not 2.83. I wasn't able to find an explanation. Creating property definitions also behaves differently. For example, in 2.91:

```
>>> bpy.types.TimelineMarker.side = bpy.props.StringProperty()
>>> m = bpy.context.scene.timeline_markers.new("marker")
>>> m.side = 'L'
>>> m.side
'L'
>>> type(m.side)
<class 'str'>
```

But, in 2.83:

```
>>> bpy.types.TimelineMarker.side = bpy.props.StringProperty()
>>> m = bpy.context.scene.timeline_markers.new("marker")
>>> m.side = 'L'
Traceback (most recent call last):
  File "<blender_console>", line 1, in <module>
AttributeError: 'TimelineMarker' object attribute 'side' is read-only
>>> type(m.side)
<class 'tuple'>
```

The [docs](https://docs.blender.org/api/current/bpy.props.html#assigning-to-existing-classes) state, "Custom properties can be added to any subclass of an ID, Bone and PoseBone." TimelineMarker does not appear to inherit from any of those classes, which would explain why this doesn't work in 2.83 but not why it _does_ work in 2.91, as nothing appears to have changed in this regard between versions.

:man_shrugging:

**Comment by aresdevo** [comment]
hmm... strange!... I wonder if it will break Animaide in future versions too. There is a simple solution but the markers would lose some versatility for the addon. That custom property is used to be able to identify the markers added by Animaide without worrying if the user changed their names. I could go back to what I had in the first version where I identified the markers by their names. The problem is that the custom property is used not only to delete the markers created by the addon but to link the reference frame to the marker (in case the user wants to modify the frame number by moving the marker).  I will try a couple of things but if I don't find another solution I will go with this one for Blender 2.83

**Comment by aresdevo** [comment]
Thanks a lot for the effort you put into it.

**Comment by avallintine** [comment]
Yeah, I see the problem. I don't know of a good solution for this, but I'm no scripting guru. As far as I'm aware, since we're not able to set a custom property on markers, the "name" property is the only reference we have available to a particular marker (that will get saved in the Blender file). Python has an id() function which will return a unique integer for a given object, for instance:

```
>>> m = bpy.context.scene.timeline_markers.new("marker")
>>> id(m)
1932265670856
```

But that's useless for our purposes because that id will change the next time the marker is re-instantiated (like when you reload the scene). I think using the name is the only way forward here, but I'd love to know if there's an alternative.

**Comment by aresdevo** [comment]
Oh, interesting the python id. I just posted a new [release for Blender 2.83](https://github.com/aresdevo/animaide/releases/tag/v1.0-LTE) with this bug fixed. I didn't find another solution. I had to use the marker's name. Everything should work the same as in the version for 2.91 if you don't rename the markers. Thanks for all the help.

**Comment by avallintine** [comment]
It works!
