### ISSUE TITLE
Anim offset doesn't work for bones with invalid f-curve channels

### ISSUE THREAD

**Issue by mahreeoocedev01** [aresdevo/animaide#35]
Sorry for re-opening the discussion, but I'm still experiencing the bug described here:
[https://github.com/aresdevo/animaide/issues/24](url)

I'll attach a file with a rig and two actions - the "anim offset - without mask" tool is working for one of them and not for the other (named them working and not_working).

The rig is a modified rigify rig.
In the "not_working" action, the only bone that can be offset is the torso control (the big cube at the hips).
In the "working" action, every bone works fine.

The one difference I can see between the two actions is that the non-working one has a few invalid f-curve channels in the graph editor, which I left on purpose, as they may be a hint (they were added by the wiggle bone addon, if I recall). But even bones with only valid channels still don't get offset.
Even if deleting the invalid channels, the anim offset still doesn't work.

I hope it's enough to get a few clues for the problem.

Thanks for all your work on this addon!

[animaide_anim_offset_bone_movement_bug.zip](https://github.com/aresdevo/animaide/files/5908594/animaide_anim_offset_bone_movement_bug.zip)

**Comment by aresdevo** [comment]
hmmm... too bad this is still an issue... I'll check to see what I find

**Comment by aresdevo** [comment]
Thanks a lot for sharing the file... it is very helpful to see the bug in an actual example.
I think I finally fixed this... check me and let me know

**Comment by mahreeoocedev01** [comment]
Everything is working fine now. Tested in Blender 2.83, 2.91 and 2.92 beta - all work.
Thank you tenfold for fixing it and for the addon :)

**Comment by aresdevo** [comment]
Oh.... perfect!... thanks for reporting this bug
