### ISSUE TITLE
Blender 2.91 AnimOffset wrong z rotation

### ISSUE THREAD

**Issue by AlloteSoftware** [aresdevo/animaide#37]
Cool addon, but if i rotate animation around Z without mask, animation broken. With mask can't move and rotate.
Version 1.0.2-LTE when installing, it gives an error.

**Comment by aresdevo** [comment]
Have not checked the rotation issue, but the error installing the addon has something to do with creating releases in GitHub. I was trying out GitHub "release" feature and it keeps adding that error to the addon... Until I solve it I won't post releases, just download from the master or from the LTE branch (meant for blender 2.83)

**Comment by aresdevo** [comment]
The problem with the installation was that GitHub adds the version number to the name of the file, and Blender doesn't like dots in the addon names. So when Blender sees animaide-1.0.2 for example disregard whatever comes after the dot. I was trying to find animaide-1 but that folder was not there. Strange, but at least I know now. I won't be using GitHub releases anymore.

**Comment by aresdevo** [comment]
I'll check the rotation issue later and will let you know what I find.

**Comment by aresdevo** [comment]
I pushed a new revision addressing another bug but it might have addressed this issue too. Please test it and let me know.

**Comment by AlloteSoftware** [comment]
Thanks, I'll check it later.

**Comment by AlloteSoftware** [comment]
Does not work. Link to test blend file [http://allote.com/share/testMixamo.rar](url)

**Comment by aresdevo** [comment]
Oh! that is exactly the same issue as this other one: https://github.com/aresdevo/animaide/issues/14
That is a feature I have not implemented yet. I'm closing this and you can follow any further development on that other link.
Thanks a lot for the file.
