### ISSUE TITLE
When using autokey anim offset turns it off... and leaves it on.

### ISSUE THREAD

**Issue by lucianomunoz** [aresdevo/animaide#38]
This is kind of in between of a bug report and a feature request, because when you're using autokey and use anim offset it turns it off and i sort of understand why, the problem is when you stop using it , it leaves it off, which has been bothering me as i keep on not noticing its off again and i lose a lot of time figuring out what happens until I remember.

Thats it other than that so far for me its perfect (i havent used it in the viewport yet, but we'll get there)

**Comment by aresdevo** [comment]
Oh!!!... sorry about that, it is supposed to restore the autokey settings you had when deactivating the tool. Maybe that got broken while fixing some bug. I'll take a look.

**Comment by lucianomunoz** [comment]
Awesome, thanks !!

**Comment by aresdevo** [comment]
Hey... there is a new publish with a fix for this. It was when I added the "Without Mask" button that I broke it, but it is solved now.

Let me know if it works

**Comment by aresdevo** [comment]
Please let me know if this works for you.
By the way, check the new "issue" I opened: https://github.com/aresdevo/animaide/issues/39
It is a place to comment on anything related to the "work in progress" branch. There I have a list of everything that is new in it. Please, if you have the time download the branch and give me any feedback you have. As far as I could test it, seems as stable as the master version.

**Comment by aresdevo** [comment]
So?... should I close this issue?

**Comment by lucianomunoz** [comment]
Oh i hadnt seen there was an update !, i'll test it now

**Comment by aresdevo** [comment]
This should be in the "work in progress" branch too

**Comment by lucianomunoz** [comment]
Now when the addon is active, i cant turn on autokey, the button stops working completely

**Comment by aresdevo** [comment]
That is exactly how it should be.... but as soon as you deactivate it, it goes back to what you had

**Comment by aresdevo** [comment]
auto key and animOffset can not coexist by nature.

**Comment by aresdevo** [comment]
but there is an option in preferences to auto-key outside the margins (when you have a mask)

**Comment by lucianomunoz** [comment]
no no, i mean even if anim offset is not active, if the addon is On autokey button does not work anymore., im not talking about animoffset.

**Comment by aresdevo** [comment]
oh... is that in master on "work in progress"?

**Comment by lucianomunoz** [comment]
Wait now it works for some reason it wasnt showing that it was active, probably a mistake on my side.
Maybe when you try to activate autokey, it should just deactivate animoffset instead of not allowing autokey to be activated?

**Comment by aresdevo** [comment]
Yes... I thought that could be an option, but honestly could not find a way... I'll keep trying.

**Comment by lucianomunoz** [comment]
No worries, or maybe a message "can use autokey with animoffset"  or something like that

**Comment by aresdevo** [comment]
True... I have an idea that might work though... I will try it... if not I will add the warning.

**Comment by lucianomunoz** [comment]
Great, by the way are you still replacing the same "work in progress.zip" link?
