### ISSUE TITLE
Testing "development" branch

### ISSUE THREAD

**Issue by aresdevo** [aresdevo/animaide#39]
# "Development" Branch

download it here:
https://github.com/aresdevo/animaide/archive/development.zip
(if the download doesn't work try to right-click and "save link as")

Please try the branch "work in progress" before I merge it to the master and give me any feedback.
These are the main changes:

CURVE-TOOLS
- Tools sorted alphabetically: 
Since I will be adding more tools I decided to sort them alphabetically in the menu and on expanded mode to make it easier to find. I also grouped them in the expanded mode (I know it might be a hassle for those that are used to the tool but I think it will make it better in the long run).
- Automatically act on keys under the cursor when no keys selected: 
If there are no keys selected and the cursor is over some keys, the CurveTools would work on those unselected keys without the need to change a preference parameter (that option is gone in the preferences since is automatic now).
- Added a new CurveTool called Blend-Infinite:
It positions the keys to match the slope of the curve on the 2 keys adjacent to it. The same as with the Tween tool, if there is no key selected and there is no key under the cursor it will add a new key for you.
- Wave was added to the Noise Tool:
This is already in master but wanted to let you know in case you have not noticed.
-Overshoot is now a button next to the preferences.

There was a change in the way the 3 ease tools work (Ease, Ease to Ease, and Blend-Ease). Now when you combine the "Wave" and "Blend-Ease" tools, for example, you get the expected result.

KEY MANAGER
Don't know if I will keep this name, but it is what I have for now. I have not added these tools to the menu or pie menus.

Move-Insert:
- Move keys or selected keys by the amount set in the "frames" field.
- Insert and subtract keys in-between the next unselected key or the selected keys by the amount set in the "frames" field.

Interpolation:
- Options to change the interpolation of keys and tangent:
Even though Blender has that ability, I've added a few options to make your life easier like instantly change the interpolation to all the keys in every curve of the object at once and changing just the first and last keys on every curve. That might be useful especially for cycles.
- Ability to select left or right handle (or both without the center point) on multiple keys at once:
That not only allows you to change the interpolation of in and out handles independently but also you can scale, move or rotate them at once. Using "Individual Centers" as a pivot point is advised. In fact, I might add that to the pannel just for convenience.

Type:
- You can change the type of a key or selection of keys:
This is mostly for organization purposes at the moment but will be very useful for future tools.
- Hide or show keys of certain types
- Delete keys of a specific type.
- If no key selected or no keys under the cursor a key will be created.

Please combine tools and let me know how it works. For example, I was trying out the handle selection tool in combination with the CurveTools and it created some interesting things. You can create a bouncing ball very easily by combining those two.

Anyway... I hope you have fun trying the new options.

**Comment by lucianomunoz** [comment]
where would i get this branch from ?

**Comment by aresdevo** [comment]
I just added a link in my first post, but here it is too:
https://github.com/aresdevo/animaide/archive/work_in_progress.zip

**Comment by lucianomunoz** [comment]
excellent, ,thank  you!

**Comment by aresdevo** [comment]
Just so you know, if you go to the main Github page of the addon, at the top left there is a pop-up menu that says "master".
if you click on it you can go to the other branches. There is one for 2.83 too (since reference frames were not working with the master version)

**Comment by lucianomunoz** [comment]
oh yeah this new branch will work fine on 2.91? im stuck on 2.91 because of the show im working oon

**Comment by aresdevo** [comment]
That is the version I'm using to test the addon mainly... so yes

**Comment by aresdevo** [comment]
One thing you might overlook because is not very obvious is that when you use handle selection tools the center one toggles between selecting the entire key (with both handles) and unselecting the middle point keeping the two handles selected.

**Comment by aresdevo** [comment]
If you have the time, please read all the point I wrote at the top... play with the tools, combine them and let me know if you have any feedback.

**Comment by aresdevo** [comment]
Also... keep the master version handy, because this one is called "work in progress" for a reason. I'll try not to upload anything unless it works, but things happen.

**Comment by lucianomunoz** [comment]
So i have some thoughts:

I feel like the panel of animaide that is in the viewport should always work for the current pose you're standing at wether it has a key or not, wether are some keys selected or not.

And the one in the animation editor should default to selected keys and keys under playhead when none are selected.
But never have the animaide in the viewport work for the selected keys as if feels confusing

Key type thing you made is great I've been envisioning this feature for some time now, in a totally different way but to do the same thing i think its pretty cool ! one thing is i think it shouldn't add new keys and color the selected ones if clicked i'd do one of the 2, or colour the selected ones  or add new keys in the current playhead position deselecting other selected keys, but not both at the same time 
Also I'd switch the eye icons for arrows as eye means visibility and arrow means selection, use the full and empty arrow from the outliner will make much more sense.

I'll come back with further thoughs as they come up, if something is not clear enough let me know and ill try to rephrase

**Comment by aresdevo** [comment]
The CurveTool suggestion make sense, i'll address that. About the arrow icon for the type tool, yes it should definitely be arrows,  don't know why i didn't think of that. The fact that the type tool is adding a key as it also applies the type to a selection is a bug, it should be one or the other. I'll check that. Thanks a lot for the feedback

**Comment by aresdevo** [comment]
Another question: Does it make sense to have the Key-Manager in the 3D viewport?
I put it there thinking that sometimes people want to work just with the timeline open and even though the panel is also in the timeline it would require expanding it too much to make the panel usable.

**Comment by aresdevo** [comment]
I'm thinking that I should remove the option that adds keys automatically in Tween and Blend-Infinite, and simply make all the tools add keys if auto-key is on (that would be more consistent with the rest of Blender). For that reason, I should try to find a way to make the autokey button available when animOffset is on, in such a way that the autokeys disable animOffset (as you said before).

I'm also thinking of finding a way in which auto-keys can have a type. For example, choosing that all the keys added automatically should be breakdown or any other type. That way you could be in an extreme poses session and then a breakdown session, etc. Let see if I can do it :P

**Comment by aresdevo** [comment]
I uploaded a new version fixing the key type bug as well as the icons. I'll address the autokey thing and the curveTools way of working in the 3D viewport later.

**Comment by aresdevo** [comment]
> I'm also thinking of finding a way in which auto-keys can have a type...
Blender already does that! ... so no need for me to do it :P

**Comment by lucianomunoz** [comment]
> 'm thinking that I should remove the option that adds keys automatically in Tween and Blend-Infinite, and simply make all the tools add keys if auto-key is on (that would be more consistent with the rest of Blender). For that reason, I should try to find a way to make the autokey button available when animOffset is on, in such a way that the autokeys disable animOffset (as you said before).

I agree with all this i think for animoffset maybe to keep autokey on it should just a key in place or overwrite the one if it exists already and transform it with the rest of the stuff, would make it consistent. But other than that i think youre in the right path.

> Blender already does that! ... so no need for me to do it :P
hahah yes,  what i'd do is to make it more accessible to your panel also same for the default tangents so in both those panels you can set what's the default tangents and default key type.

**Comment by aresdevo** [comment]
This branch should be more stable at this point.
- Most of the tools ("sliders") can add keys when autokey is enabled. I still let the tools modify keys under the cursor even without autokey on because I felt it needed to be like that, but you let me know. 
_One thing that is not as I wanted it to be is that if the auto-key is not active and there is no key under the cursor the tools don't affect the object (or bone) at all. I thought it would have been a nice thing to have since you may want to add one key without having auto-key selected. The solution is to add the key and then use the tool for now._
- The tools don't work on selected keys when used from the viewport. The panel should be named differently or something to differentiate them from the ones in the anim views though. Or maybe add an option so the user chooses if they want that behavior.
- Added a blender button to key-type section of the keyManager panel to choose the type of key that will be added when setting a key or the auto-key is on.
- Added a blender button to the interpolation section of keyManager, more specifically when the "Bezier" option is selected, that lets you choose the povot point of the manipulation.

**Comment by lucianomunoz** [comment]
Great, im downloading now!

**Comment by aresdevo** [comment]
Oops... Noticed a bug using curve tools in the 3d view with autokey on... it gives an error... fixing it now

**Comment by aresdevo** [comment]
I'm cleaning up the interface. We don't need to have the curveTools in the dopesheet and timeline for example. Also, a lot of curve tools don't make much sense in the 3d view if it is only going to affect the current frame.

**Comment by lucianomunoz** [comment]
Great, by the way are you still replacing the same "work in progress.zip" link?

**Comment by aresdevo** [comment]
yes... but I realized the work in progress version is not as stable as I thought... let me work on it a few more days

**Comment by aresdevo** [comment]
There is a new version of this branch. Download the zip on the link. If for some strange reason it doesn't work try right-clicking and "save link as".

**Comment by aresdevo** [comment]
I tried to fix every bug I could find but I'm sure there might be some that scaped me.
In terms of the new things here are the main ones:
- Anim Offset is not on a panel anymore. you can find buttons on the animation editors' headers. The button work in a more intuitive manner now. AnimOffset activation button works as a toggle like before, but the mask button now has that same behavior. When you create a mask a new button appears that lets you modify the mask. The mask creation process has the same options as before but now the "modify mask" button is persistent (modal).
- Added addon preferences (On the addon tab in the Blender preferences where you first installed it). The advantage of those preferences is that they stay the same even after quitting Blender.
- Using that new preference option you can now choose to have "Key Manager" on a panel or on animation editors headers
- As I mentioned before now the curve tools in the 3D View work only on current frames (they disregard selection). For that reason, I just kept the ones that made sence. Others simply would do basically the same as some of the ones that are there already.
- Menus are simpler now.
- Tools are only in the areas they make sense now.
- Key-type deletion now work on selected keys, not on every key. I thought it made more sense to delete a key-type among the selected keys than to simply delete all of them.
- Added a "sticky handles" option to the CurveTools. Mainly works when keys have "Free" and "Aligned" handle types. Handles will mostly stay in place as the center keypoint gets affected by the curveTools.

**Comment by aresdevo** [comment]
I'm almost ready to merge it to master, the main thing now is to modify the reed-me

**Comment by aresdevo** [comment]
Just changed the name of the branch to "development"

**Comment by aresdevo** [comment]
Just merged the development branch to master, so at the moment they are both the same.
