### ISSUE TITLE
Auto IK doesn't work Anim Transform

### ISSUE THREAD

**Issue by Irmitya** [aresdevo/animaide#4]
What Auto IK does is allow you temporarily add an IK constraint to bones when they're connected (an FK chain), so that you can pose them like you would with an IK controller. 
When you confirm the pose, Blender removed the Temporary IK constraint and applies the pose. 

Upon applying the pose with Anim Transform activated, the pose just resets. 
Sometimes it also does a pose offset on ONE of the bones in the chain but it's completely incorrect.

**Comment by aresdevo** [comment]
Oh wow, never tried it with Auto Ik!!! I love that tool and never thought of trying AnimAide with it. Thanks for reporting this... I will take a look.

**Comment by aresdevo** [comment]
Auto-IK seems to be working now. Let me know if it works for you.
