### ISSUE TITLE
The zip folder is invalid and cannot be opened

### ISSUE THREAD

**Issue by IronLover64** [aresdevo/animaide#41]
![Screenshot (15)](https://user-images.githubusercontent.com/51809607/111912091-7de99e80-8a3e-11eb-864d-c8cbf6492172.png)

**Comment by aresdevo** [comment]
Strange!... can not replicate that on my Mac. I'll try latter on a PC.
Hold on tight... I'm about to release a new version, so maybe by the time that issue is solved the new version will be up.

**Comment by aresdevo** [comment]
I just tried on my PC and can not replicate it either. As referred on the previous post, I just pushed a new version of the addon, so try again and maybe it will work this time. I if doesn't work explain with more detail what your process was and maybe I can help you troubleshoot this.

**Comment by aresdevo** [comment]
Can not reproduce this error, so I'm closing this issue. If you want to reopen it let me know
