### ISSUE TITLE
Unable to open addon

### ISSUE THREAD

**Issue by JamesTroici** [aresdevo/animaide#53]
![unknown](https://user-images.githubusercontent.com/77027862/134070603-f6c05ed0-ee51-4f8e-a03e-644d1aa2f844.png)

I re-downloaded the addon today but still no luck. When I install the addon and try to click the box to turn it on that error pops up.

Not sure if this is an issue on my end but I only have this issue when installing this addon lately.

Thanks!

**Comment by Sobollion** [comment]
Same thing, but other error

Traceback (most recent call last):
  File "D:\Steam\steamapps\common\Blender\3.0\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\Sobollion\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\animaide-master\__init__.py", line 46, in <module>
    class AnimAideScene(PropertyGroup):
  File "C:\Users\Sobollion\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\animaide-master\__init__.py", line 48, in AnimAideScene
    tool: PointerProperty(type=curve_tools.props.AnimAideTool)
AttributeError: module 'animaide-master.curve_tools.props' has no attribute 'AnimAideTool'

**Comment by Sobollion** [comment]
I think it might help! 
https://wiki.blender.org/wiki/Reference/Release_Notes/2.93/Python_API

**Comment by Sobollion** [comment]
So all you want to do is change "=" to ":" in line 67 of https://github.com/aresdevo/animaide/blob/master/__init__.py
I am already create pull request for this

**Comment by aresdevo** [comment]
The patch has been merged. Thanks @Sobollion

**Comment by Sobollion** [comment]
@aresdevo well i tested it and now it stucks on that:

Python: Traceback (most recent call last):
  File "C:\Users\Sobollion\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\animaide-master\curve_tools\ui.py", line 184, in draw
    animaide = context.scene.animaide
AttributeError: 'Scene' object has no attribute 'animaide'

location: <unknown location>:-1

Python: Traceback (most recent call last):
  File "C:\Users\Sobollion\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\animaide-master\anim_offset\ui.py", line 35, in draw
    anim_offset = context.scene.animaide.anim_offset
AttributeError: 'Scene' object has no attribute 'animaide'

location: <unknown location>:-1

**Comment by aresdevo** [comment]
Oh!... I know what that is... I thought I had solved that!... let me check

**Comment by aresdevo** [comment]
Well... it turns out the "=" was needed there instead of the ":". I should have checked before pushing the change. But, when that error happened I saw the error @JamesTroici started this with. I reverted to what it was before, but I'm going to check on the original error because I think I might know what the problem is now.

**Comment by Sobollion** [comment]
Okay, sorry for that! Hope you'll find the solution

**Comment by aresdevo** [comment]
No worries, it led me to something :)

**Comment by aresdevo** [comment]
Well... I think the problem might be fixed. If still continues let me know. But for sure I fixed some issues with the way you can choose to put the tools on the header or on a panel. It was causing a bunch of errors, including this one. So hopefully it solves this bug too.

**Comment by aresdevo** [comment]
This bug seems to be fixed
