### ISSUE TITLE
Add-on does not want to activate again and gives me this error

### ISSUE THREAD

**Issue by marksman230591** [aresdevo/animaide#55]
![Animaide_error](https://user-images.githubusercontent.com/93716674/140316962-3a7b08e3-896f-4c3e-9fdb-1540965d1fbc.png)

**Comment by zafirf** [comment]
Same issue!

**Comment by aresdevo** [comment]
I'll take a look. One question, did you have an older version of the addon when you installed the current one?

**Comment by aresdevo** [comment]
Somebody submitted a patch to solve this. It should be fixed now. Let me know if not.

**Comment by aresdevo** [comment]
This is the same as issue #53. I fixed something that was giving me this error so hopefully this bug is gone. Let me know if it works.

**Comment by aresdevo** [comment]
This bug seems to be fixed
