### ISSUE TITLE
Anim offset doesn't working sometimes. 

### ISSUE THREAD

**Issue by juanchomilano19** [aresdevo/animaide#56]
Hey! First of all, thank you so much for the addon, is really amazing and a time saver. 

My only issue with it is that sometimes the anim offset option doesn't work at all for some specific bones of the rig. I've not been able to find why it is this happens, but when I have an advanced animation, some Ik bones don't move when the option is activated, or, if I active the "fast calculation" option, the bones can move but immediately returns to the same place, so they same big is happening there. 

![ezgif com-gif-maker](https://user-images.githubusercontent.com/12436667/141365475-0ea41511-29ef-4c75-8126-2cc5872fd2b7.gif)

This is an example of what I am talking about. In that scene, I have two characters, when I activate the anim offset, it doesn't work in the root of one of them (the controller just doesn't move) but it works perfectly in the other one. This same happens to me with any other control but is way more often with the ik controllers.

**Comment by aresdevo** [comment]
Thanks for reporting this bug

**Comment by aresdevo** [comment]
I'll take a look, thanks for being so thorough on your explanation

**Comment by aresdevo** [comment]
Sorry, have not been able to check this, life has been kind of crazy lately. I think at the end of this month I will have the time.

**Comment by aresdevo** [comment]
I had a couple of days coding and addressing a bunch of bugs. I haven't fully checked this one, but let me know if it is still there because maybe I addressed it with the other bug fixes.

**Comment by aresdevo** [comment]
@juanchomilano19, I had a couple of days coding and addressing a bunch of bugs. I haven't fully checked this one, but let me know if it is still there because maybe I addressed it with the other bug fixes.
