### ISSUE TITLE
Place images in Wiki repo [IDEA]

### ISSUE THREAD

**Issue by schroef** [aresdevo/animaide#57]
Perhaps an idea to place the images in a wiki repo so your main repo stays clean and small.
On the other hand, having them included does allow for a user to easily check how to.

**Comment by aresdevo** [comment]
I might try that. Thanks.

**Comment by aresdevo** [comment]
I finally did something similar to what you suggested. I created a [GitHub page](https://aresdevo.github.io/animaide/) and put all the images there. The readme file now is referring to those instead.
