### ISSUE TITLE
AnimOffset doesn't work when you add keyframes for rotation order in 2.93

### ISSUE THREAD

**Issue by CzarWG** [aresdevo/animaide#58]
Running Blender 2.93.0 with addon version 1.0.33

When I wanted to offset some bone in my animation, it just wouldn't work. I thought it happened randomly as only this function wouldn't want to work only on some bones but turns out it's because of keyframed rotation order. I only had two bones with keyframed rot order but there were many others that just didn't work for some reason.

I did some debugging and found out that in `get_delta` function in `anim_offset/support.py` script, line 207 tried to subtract string from float (because it took X from rotation order fcurve)
![image](https://user-images.githubusercontent.com/73833874/143885062-40fb56a7-def5-4381-bbb1-f7053a17589f.png)
This is after some debugging

I didn't have much time to try and properly reproduce this but it did happen to me multiple times already. Please add some exception for rot order curves evaluation, it's hard to work sometimes without keying them.

**Comment by CzarWG** [comment]
One quick fix I can suggest is to add an if statement when the fcurves are listed under the `line 88` in `anim_offset/support.py` script

```py
if fcurve.data_path.endswith("rotation_mode"): continue
magnet(context, obj, fcurve)
```

**Comment by aresdevo** [comment]
Thanks @CzarWG. I added the line and pushed the change. I have not tested it. Let me know if it works
