### ISSUE TITLE
Anim Offset with Mask gives an error in 1.0.33

### ISSUE THREAD

**Issue by DmitryPechkin** [aresdevo/animaide#61]
Anim Offset with Mask gives an error in 1.0.33. Works fine without mask.
Works fine in 1.0.1 both with Mask and without.
Same in Blender Blender 2.93 and 3.0.

To replicate:
Open default Cube scene, add two location keyframes to Cube.
Use AnimOffset with Mask from Dope Sheet.
Include second keyframe in Mask range, move cube.
Press Deactivate.

<img width="916" alt="AnimOffsetError" src="https://user-images.githubusercontent.com/96837946/147686908-94b9b6ff-3576-4bfa-be0b-63921a83cf99.png">

**Comment by aresdevo** [comment]
Interesting... Thanks for catching that

**Comment by aresdevo** [comment]
I pushed a new version addressing this bug. hopefully, it worked. Please download it and let me know.

**Comment by DmitryPechkin** [comment]
It works great! Thank you! Very useful addon.

**Comment by aresdevo** [comment]
Glad it worked. Thanks for letting me know.
