### ISSUE TITLE
Problems Disabling addon without Disabling Anim Transform

### ISSUE THREAD

**Issue by Irmitya** [aresdevo/animaide#7]
Anim Transform adds a function to `depsgraph_update_pre` without checking if it's already there
(and the remove tries the same but reverse)

If you Activate  the Anim Transform function, then turn off the addon without first clicking deactivate, the transform function will continue to run. 

There will be problems after this occurs as well. 

Rather than elaborate on the problems you'd run into, the solution would be to remove the transform and mask functions if they're in `depsgraph_update_pre`, during the `unregister` function.

**Comment by aresdevo** [comment]
Oh.... good catch. thanks

**Comment by aresdevo** [comment]
I added a test to check if the handler has the function before adding or deleting. Also, remove them when unregistering.
