### ISSUE TITLE
Smooth behaving weirdly

### ISSUE THREAD

**Issue by monkeez** [aresdevo/animaide#70]
When I use smooth on a noisy curve it doesn't seem to smooth the curve in a natural way. It looks like it's pushing the keys to the right whilst smoothing them:

![smooth](https://user-images.githubusercontent.com/5214414/155076312-01be6d9c-b98e-44d4-93ed-46a298687723.gif)

**Comment by aresdevo** [comment]
Interesting!... let me take a look

**Comment by aresdevo** [comment]
I pushed a new [version](https://github.com/aresdevo/animaide/releases/tag/v1_0_38_3) fixing this bad behavior. Let me know if it works.

**Comment by monkeez** [comment]
Yup it's working now. Thanks!
