### ISSUE TITLE
I uncovered a bug anim offset isn't working in 3.1

### ISSUE THREAD

**Issue by mjoe67887** [aresdevo/animaide#73]
I'm trying to change the location of a character I imported using the daz to blender add on. It is a genesis 8 character. She has face animations. I was trying to use the anim offset in 3.1 to move her to a different location. But I'm getting the cannot convert float to int error... It works OK in 3.0 1

**Comment by aresdevo** [comment]
OH... thanks for reporting this. I'll take a look as soon as I can. in the meantime check to see if a [previous version](https://github.com/aresdevo/animaide/releases) doesn't have this bug.
