### ISSUE TITLE
Scene.frame_current expected an int type, not float error

### ISSUE THREAD

**Issue by mjoe67887** [aresdevo/animaide#74]
I keep getting this error when I'm trying use the anim offset tool. First it happened on a character I brought into blender with the daz to blender bridge so I thought it was an issue related to that but now it's happening when animating just a basic mesh object ....this is happening in blender 3.1

**Comment by mjoe67887** [comment]
Thank you so much I really like this add on

**Comment by aresdevo** [comment]
Can you give me a specific example of when this error happened? That would help me pin-point the issue

**Comment by aresdevo** [comment]
oh... I see you have an example on the other report

**Comment by aresdevo** [comment]
I can not reproduce the bug, but I have a newer version of the addon. Let me finish something I'm adding to it and then after I push the new version you can test it again to see if you still get the error.

**Comment by aresdevo** [comment]
By the way... glad you like the addon. I can not take much credit for it, I'm just bringing to Blender things I've used in the industry as an animator.

**Comment by mjoe67887** [comment]
Yeah this add-on is seriously amazing..do you still need example?

**Comment by aresdevo** [comment]
Oh... sorry, have been busy. Yes please, if you can give me an example of how that error happens would be amazing.

**Comment by Dhruvin743** [comment]
i have also faced this issue.
when we try to use anim offset mask. 

![Screenshot (27)](https://user-images.githubusercontent.com/37476829/160844172-7490d064-05e8-4ad9-9bb5-39c458461470.png)

after selecting range for mask it gives this error without mask addon works fine.

**Comment by RiggingDojoAdmin** [comment]
This is happening with all tools using current frame, something changed in python someone mentioned.

**Comment by RiggingDojoAdmin** [comment]
There is a new? >>> bpy.context.scene.frame_float that takes Floats but frame_current is now INT

**Comment by RiggingDojoAdmin** [comment]
Python's automatic conversion from decimals to Ints in 3.10

**Comment by mjoe67887** [comment]
here is my example....If I click anim offset and mask in pose mode with all
the controllers selected i get this  RuntimeError: Error: Use
'Time_Translate' transform mode instead of 'Translation' mode for
translating keyframes in Dope Sheet Editor

if I deselect them all then reselect them right after and then run anim
offset and mask i get : Scene.frame_current expected an int type, not float
 RAIN character from the blender website on a brand new file of it on 3.1
of course  my blender file is right here
https://drive.google.com/file/d/1rUOomAGcz8Ab86eUceU7n5uIXxUneXEF/view?usp=sharing

**Comment by aresdevo** [comment]
Sorry guys, life is getting in the way, I'm in a pickle at the moment but as soon as I'm in a calmer state I will address this issue.

**Comment by aresdevo** [comment]
Well, @Festivize did the work for me. Thanks so much!
I created a new [version](https://github.com/aresdevo/animaide/releases/tag/v1_0_38_31) with his commit. I have not tested it, so let me know if the problem is solved.

**Comment by Morphinometr** [comment]
>  I created a new [version](https://github.com/aresdevo/animaide/releases/tag/v1_0_38_31) with his commit.

Unfortunately, there is a bug in version too. This happens when first activate AnimOffset Mask.

![image](https://user-images.githubusercontent.com/20975841/162977431-b19f0cad-76b9-4d70-ae38-f16c3276282f.png)

**Comment by DmitryPechkin** [comment]
> > I created a new [version](https://github.com/aresdevo/animaide/releases/tag/v1_0_38_31) with his commit.
> 
> Unfortunately, there is a bug in version too. This happens when first activate AnimOffset Mask.
> 
> ![image](https://user-images.githubusercontent.com/20975841/162977431-b19f0cad-76b9-4d70-ae38-f16c3276282f.png)

I think I fixed it by changing file curve.py located in %AppData%\Blender Foundation\Blender\3.1\scripts\addons\animaide-master\utils
LINE 56 FROM: bpy.ops.transform.translate(value=(0, 0, 0))
LINE 56 TO: bpy.ops.transform.transform(mode='TIME_TRANSLATE', value=(0, 0, 0, 0))

I have not used it extensively but it seems to work with this change.

**Comment by aresdevo** [comment]
Sorry for the delay. I have not been actively working on the addon. There is a contribution that fixed this error. There is a new [release](https://github.com/aresdevo/animaide/releases/tag/v1_0_38_32) with the fix
