### ISSUE TITLE
Suggestion: Anim Transform: Allow changing ranging without the sliders

### ISSUE THREAD

**Issue by Irmitya** [aresdevo/animaide#8]
I noticed that if you manually change the scene.frame_preview_start/end values while using Anim Transform, they will automatically reset back to whatever's in the mask's property.

Blender has a operator [View >> Set Preview Range (hotkey: P)]
that lets you box select the start/end range of the timeline. 

I would prefer to be able to visually select the range of which the mask is running. 

You could have the depsgraph_update_pre function update the scene mask numbers when the timeline's values change. 

- - - - -

Another idea (based on SFM's motion editor) is to have setting the mask with a macro box selector. 

What I mean by that is when you click add mask, it 
1) starts the set preview box selector and saves that range, then
2) starts the set preview box selector again and saves that range, 
3) finally it sets those values as the margin and the blends. 

It could do a blend only comparing the final numbers but that would make doing a "No Blend" selection difficult. You could probably cancel the second one to do that but I don't know if a macro list can continue if one is cancelled. 

The way it works in SFM is you select a hard/margin range _(using the time-slider)_, then if you run the selection again, you set a blend range.

**Comment by aresdevo** [comment]
When thinking about ideas of how to show the mask I realized I could hijack the preview and playback ranges for a bit while the tools were active. I thought about trying to add the range with a box as you say but didn't find an intuitive way of telling the user how to create the range. But your suggestion at the end could be a good way.

**Comment by aresdevo** [comment]
This has been addressed... thanks
