### ISSUE TITLE
Animation offset doesn't work in 3.1.2 version

### ISSUE THREAD

**Issue by LissaManbawaran** [aresdevo/animaide#88]
Hello! Thank you for such a nice addon. I'm using Blender version 3.1.2 and the Animation Offset option doesn't work for me. All other options are there. I enabled offset animation separately in the settings, but this feature is still not available. Please help me.
![issue_3 2 1](https://user-images.githubusercontent.com/68732155/213382421-9530d779-c451-4d30-97d1-4d33db76f114.png)

**Comment by aresdevo** [comment]
Thanks @abrasic
